### ISSUE TITLE
Warns when reloading, but reloading still works.

### ISSUE THREAD

**Issue by SenchoPoro42** [Hetag1216/AreaReloader#4]
It happens almost 100% of the time one of the currently 6 areas reloads.
It doesn't stop the reloading from functioning, it just clogs up the console.

```
[15:52:38 WARN]: [AreaReloader] Task #320 for AreaReloader v1.6 generated an exception
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.remove(ArrayList.java:535) ~[?:?]
        at com.hetag.areareloader.AreaLoader.progressAll(AreaLoader.java:112) ~[?:?]
        at com.hetag.areareloader.AreaLoader.access$0(AreaLoader.java:84) ~[?:?]
        at com.hetag.areareloader.AreaLoader$1.run(AreaLoader.java:119) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1203) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1121) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by Hetag1216** [comment]
Hello!
Could you please provide your server's version and worldedit's version?
Does the issue happen when manually loading areas via the /ar load command or via automatic reloading using area scheduler?
If the issue happens when manually loading areas, is the process completing up to 100% and sending a confirmation message that the area's been loaded correctly?
Could you also please provide logs with the debugging mode on?

**Comment by SenchoPoro42** [comment]
Oh yea, my bad, didn't read the notes about issues quite well enough on the spigot page!
MC 1.15.2 on Tuinity with Java v 11.
Worldedit 7.1.0.
Only happens with the autoreload, just restarted with debug on, the warn still came immediately upon restart. The debug mode didn't seem to change anything for the auto reloading, only the manual ones.
I've never seen a status message on the reloading, it just says automatically reloading and that's it.

```
[16:36:38 INFO]: [AreaReloader] Automatically reloading area: jobcenter-carrot-farm-1
[16:36:38 INFO]: [AreaReloader] Automatically reloading area: jobcenter-carrot-farm-3
[16:36:38 INFO]: [AreaReloader] Automatically reloading area: jobcenter-carrot-farm-6
[16:36:38 WARN]: [AreaReloader] Task #320 for AreaReloader v1.6 generated an exception
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.remove(ArrayList.java:535) ~[?:?]
        at com.hetag.areareloader.AreaLoader.progressAll(AreaLoader.java:112) ~[?:?]
        at com.hetag.areareloader.AreaLoader.access$0(AreaLoader.java:84) ~[?:?]
        at com.hetag.areareloader.AreaLoader$1.run(AreaLoader.java:119) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1203) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1121) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by Hetag1216** [comment]
No worries!
I can see that you're automatically reloading three different areas at the same time.
That might be what's causing the warning to pop up; whenever an area is being loaded there's a checker which checks its "requisites" and prevents the area to be loaded multiple times upon a single call in order to not cause insane lag and in the worst case "break" your server (if you're wondering if it could cause any issues to your server, don't worry, it won't).
What you could try to do is delay the auto reloading time for the areas you want to automatically reload and put a different loading time for all three.
Let me know if the issue persists! :)

**Comment by SenchoPoro42** [comment]
Glad to hear it, I'll adjust them to be more different, and then also block the warn from the console.
